title: Getting Started With Mathematica
hero_image: images/banner.png
description: Getting started with Mathematica and the Wolfram language on Raspberry Pi
original_url: https://raspberrypi.org/learning/getting-started-with-mathematica
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: 
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Getting started with Mathematica
- title: Starting Mathematica
- title: Programming in Mathematica
- title: Wolfram command line access
- title: List operations
- title: Matrices
- title: Plotting
- title: GPIO
- title: Camera

